#!/bin/bash
#Menu
clear
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "* menu            : List of Main Commands"
echo -e "* usernew         : Creating SSH & OpenVPN accounts"
echo -e "* trial           : Membuat akun trial"
echo -e "* hapus           : Deleting SSH & OpenVPN accounts"
echo -e "* cek             : Check user login"
echo -e "* cekconfig       : Check the available config"
echo -e "* member          : SSH & OpenVPN member list"
echo -e ""
echo -e "=============================-SYSTEM-=========================="
echo -e "* restart         : Restart service Openssh,Dropbear"
echo -e "                    Stunnel,OpenVPN dan Shadowsocks"
echo -e "* reboot          : Reboot VPS"
echo -e "* speedtest       : Speedtest VPS"
echo -e "* info            : Display system information"
echo -e "* about           : Info script auto install"
echo -e "* exit            : Exit PuTTY/Connectbot/"
echo -e ""
